version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    profiles:
      - dev

  db:
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    profiles:
      - dev

  backend-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db-tests
    profiles:
      - test 
    command: npm test
  
  frontend-tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    profiles:
      - test 
    command: npm test

  db-tests:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    ports:
      - "5433:5432"
    profiles:
      - test

volumes:
  postgres_data: 